<a href="https://colab.research.google.com/github/TREX99/python.ai/blob/master/3%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
from scipy import linalg as la

e = np.array([1, 0, 0])
A = np.array([[7, 2, 0], [2, 1, 3], [4, 8, 3]])
a = A[:, 0]

a - la.norm(a) * e

array([-1.30662386,  2.        ,  4.        ])

In [22]:
import numpy as np
from scipy import linalg as la

e = np.array([1, 0, 0])
A = np.array([[7, 2, 0], [2, 1, 3], [4, 8, 3]])
a = A[:, 0]

u = a - la.norm(a) * e
u / la.norm(u)

array([-0.28044521,  0.42926693,  0.85853386])

In [27]:
import numpy as np
from scipy import linalg as la

e = np.array([1, 0, 0])
I3 = np.array([[1, 0, 0],[0, 1, 0],[0, 0, 1 ]])
A = np.array([[7, 2, 0], [2, 1, 3], [4, 8, 3]])
a = A[:, 0]


u = a - la.norm(a) * e
v = u / la.norm(u)
I3 - 2 * v * v.T

array([[ 0.84270097, -0.36854019, -1.47416078],
       [-0.15729903,  0.63145981, -1.47416078],
       [-0.15729903, -0.36854019, -0.47416078]])

In [28]:
import numpy as np
from scipy import linalg as la

e1 = np.array([1, 0, 0])
I3 = np.eye(3)
A = np.array([[7, 2, 0], [2, 1, 3], [4, 8, 3]])
a = A[:, 0]

u = a - (la.norm(a) * e1)  
v = u / la.norm(u)  # 정규화
Q1 = I3 - 2 * v * v.T
Q1 @ A

array([[ -0.7348167 , -10.47642447,  -5.52810291],
       [ -5.7348167 , -11.47642447,  -2.52810291],
       [ -3.7348167 ,  -4.47642447,  -2.52810291]])

아래부터는 검증을 위한 프로그램입니다.

In [172]:
import numpy as np
from scipy import linalg as la

e1 = np.array([1, 0, 0])
I3 = np.eye(3)
A = np.array([[7, 2, 0], [2, 1, 3], [4, 8, 3]])
a = A[:, 0]

print("a")
print(a, la.norm(a))
u = a - (la.norm(a) * e1)  
print("u")
print(u)
v = u / la.norm(u)  # 정규화
print("v")
print(v)

print("I3")
print(I3)
Q1 = I3 - 2 * v * v.T
print("Q1")
print(Q1)

print("result")
print(Q1 @ A)

a
[7 2 4] 8.306623862918075
u
[-1.30662386  2.          4.        ]
v
[-0.28044521  0.42926693  0.85853386]
I3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Q1
[[ 0.84270097 -0.36854019 -1.47416078]
 [-0.15729903  0.63145981 -1.47416078]
 [-0.15729903 -0.36854019 -0.47416078]]
result
[[ -0.7348167  -10.47642447  -5.52810291]
 [ -5.7348167  -11.47642447  -2.52810291]
 [ -3.7348167   -4.47642447  -2.52810291]]
