<a href="https://colab.research.google.com/github/TREX99/python.ai/blob/master/3%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import numpy as np

A = np.array([[7, 2, 0], [2, 1, 3], [4, 8, 3]])

np.diag(A[[0, 1, 2], [0, 1, 2]])

array([[7, 0, 0],
       [0, 1, 0],
       [0, 0, 3]])

In [59]:
import numpy as np

A = np.array([[7, 2, 0], [2, 1, 3], [4, 8, 3]])

B = A.T @ A 

B == B.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [60]:
import numpy as np

B = np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]])

# 직교행렬의 정의에 따라 A.T@A = A@A.T 이며 그 값이 항등행렬이어야 한다.

print(B @ B.T == B.T @ B)
print("-------------------")
print(B.T @ B)



[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
-------------------
[[1 0 0]
 [0 1 0]
 [0 0 1]]
